const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");
const { execFileSync } = require("node:child_process");
const { createCipheriv, createDecipheriv, randomBytes, createHash } = require("node:crypto");
const { createBackup, restoreBackup } = require("./backup");

test("an existing desktop database survives migration and an encrypted restore", { timeout: 60_000 }, async () => {
  const { PGlite } = await import("@electric-sql/pglite");
  const { drizzle } = await import("drizzle-orm/pglite");
  const { migrate } = await import("drizzle-orm/pglite/migrator");
  const folder = await fs.mkdtemp(path.join(os.tmpdir(), "kct-migration-"));
  let database;
  try {
    const legacy = path.join(folder, "legacy");
    await fs.mkdir(path.join(legacy, "meta"), { recursive: true });
    await fs.copyFile("drizzle/0000_init.sql", path.join(legacy, "0000_init.sql"));
    const journal = JSON.parse(await fs.readFile("drizzle/meta/_journal.json", "utf8"));
    journal.entries = journal.entries.slice(0, 1);
    await fs.writeFile(path.join(legacy, "meta", "_journal.json"), JSON.stringify(journal));
    const live = path.join(folder, "live");
    await fs.mkdir(live, { recursive: true });
    database = new PGlite(path.join(live, "database"));
    await migrate(drizzle(database), { migrationsFolder: legacy });
    const key = randomBytes(32);
    const encrypt = value => {
      const iv = randomBytes(12);
      const cipher = createCipheriv("aes-256-gcm", key, iv);
      const ciphertext = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]);
      return ["v1", iv.toString("base64"), cipher.getAuthTag().toString("base64"), ciphertext.toString("base64")].join(":");
    };
    const account = encrypt("012345678901");
    const factor = encrypt("EXISTINGAUTHENTICATOR");
    const user = (await database.query("INSERT INTO users(email, name, role, password_hash, session_version, totp_enabled, totp_secret_enc) VALUES ('existing@example.test', 'Existing user', 'ADMIN', 'existing-hash', 7, true, $1) RETURNING id", [factor])).rows[0].id;
    const client = (await database.query("INSERT INTO clients(name) VALUES ('Existing client') RETURNING id")).rows[0].id;
    const supplier = (await database.query("INSERT INTO counterparties(legal_name) VALUES ('Existing supplier') RETURNING id")).rows[0].id;
    const caseId = (await database.query("INSERT INTO cases(reference, client_id, counterparty_id, decision_purpose, created_by_id) VALUES ('KC-2026-0001', $1, $2, 'Existing decision', $3) RETURNING id", [client, supplier, user])).rows[0].id;
    await database.query("INSERT INTO payment_instructions(counterparty_id, case_id, beneficiary_name, bank_name, account_enc, account_last4, source_description, created_by_id) VALUES ($1, $2, 'Existing supplier', 'Existing bank', $3, '8901', 'Existing instruction', $4)", [supplier, caseId, account, user]);
    const capture = Buffer.from("Existing source capture");
    await fs.mkdir(path.join(live, "documents"));
    await fs.writeFile(path.join(live, "documents", "existing.txt"), capture);
    await database.query("INSERT INTO documents(case_id, original_name, stored_name, mime_type, size_bytes, sha256, doc_type, uploaded_by_id) VALUES ($1, 'existing.txt', 'existing.txt', 'text/plain', $2, $3, 'Source capture', $4)", [caseId, capture.length, createHash("sha256").update(capture).digest("hex"), user]);
    await migrate(drizzle(database), { migrationsFolder: "./drizzle" });
    const { rows } = await database.query("SELECT name, password_hash, session_version, must_change_password, failed_mfa_attempts FROM users WHERE email='existing@example.test'");
    assert.deepEqual(rows[0], { name: "Existing user", password_hash: "existing-hash", session_version: 7, must_change_password: false, failed_mfa_attempts: 0 });
    await database.close();
    database = null;
    const config = JSON.stringify({ dataEncryptionKey: key.toString("base64") });
    await fs.writeFile(path.join(live, "config.json"), config);
    const backup = path.join(folder, "snapshot.kctbackup");
    await createBackup(live, backup, "separate-recovery-password");
    const restore = path.join(folder, "restore");
    await restoreBackup(backup, restore, "separate-recovery-password");
    database = new PGlite(path.join(restore, "database"));
    await migrate(drizzle(database), { migrationsFolder: "./drizzle" });
    const restored = await database.query("SELECT name, session_version, totp_secret_enc FROM users WHERE email='existing@example.test'");
    assert.deepEqual(restored.rows[0], { name: "Existing user", session_version: 7, totp_secret_enc: factor });
    assert.equal(await fs.readFile(path.join(restore, "config.json"), "utf8"), config);
    const bank = (await database.query("SELECT account_enc FROM payment_instructions WHERE case_id=$1", [caseId])).rows[0].account_enc;
    assert.equal(bank, account);
    const [, iv, tag, ciphertext] = bank.split(":");
    const restoredKey = Buffer.from(JSON.parse(await fs.readFile(path.join(restore, "config.json"), "utf8")).dataEncryptionKey, "base64");
    const decipher = createDecipheriv("aes-256-gcm", restoredKey, Buffer.from(iv, "base64"));
    decipher.setAuthTag(Buffer.from(tag, "base64"));
    assert.equal(Buffer.concat([decipher.update(Buffer.from(ciphertext, "base64")), decipher.final()]).toString("utf8"), "012345678901");
    assert.equal(await fs.readFile(path.join(restore, "documents", "existing.txt"), "utf8"), capture.toString("utf8"));
    await database.close();
    database = null;
    const password = "recovery-test-password";
    const result = execFileSync(process.execPath, ["scripts/recover-admin.mjs", "--email", "existing@example.test"], { encoding: "utf8", input: `${password}\n`, env: { ...process.env, DATABASE_URL: "", PGLITE_DIR: path.join(restore, "database") } });
    assert.match(result, /Administrator recovered/);
    assert.equal(result.includes(password), false);
    database = new PGlite(path.join(restore, "database"));
    const recovered = await database.query("SELECT must_change_password, session_version, totp_enabled FROM users WHERE email='existing@example.test'");
    assert.deepEqual(recovered.rows[0], { must_change_password: true, session_version: 8, totp_enabled: false });
    const audits = await database.query("SELECT action FROM audit_events WHERE action='auth.admin_recovered'");
    assert.equal(audits.rows.length, 1);
  } finally {
    await database?.close();
    await fs.rm(folder, { recursive: true, force: true });
  }
});
